# oVirt

https://bugzilla.redhat.com/1780910

The issue: When trying to move a Storage Domain to maintenance with the "Ignore OVF" failures checked, the StorageDomain would move not move to maintenance, but rather move to Inactive status.

### Original hypothesis

Moving a host from Preparing to Maintenance status to Maintenance is an asynchronous action. A Storage Domain is first moved to "Preparing to Maintenance", and will be move to Maintenance after `IrsProxyImpl#proceedStoragePoolStats` runs and submits it into an event queue responsible for Storage Domain and Datacenter operations.

The assumption is that because this action is asynchronous, the Storage Domain monitor handled the Storage Domain and moved it inactive when it discovered no hosts are connected to it.

No evidence supporting this were found.

### Actual Solution

Looking at the logs, we can see the Storage Domain is moved to unknown at the end of `DeactivateStorageDomainWithOvfUpdateCommand`:
```
2020-06-02 06:25:59,277-04 INFO  [org.ovirt.engine.core.bll.CommandCompensator] (EE-ManagedScheduledExecutorService-engineScheduledThreadPool-Thread-24) [732e86f2] Command [i
d=25e72684-aae9-4ae5-bdea-3d93e1a74556]: Compensating CHANGED_STATUS_ONLY of org.ovirt.engine.core.common.businessentities.StoragePoolIsoMap; snapshot: EntityStatusSnapshot:{
id='StoragePoolIsoMapId:{storagePoolId='b2db29b8-8d57-11ea-ab1e-5254000240eb', storageId='bed8b820-752d-4dec-a3d4-a5e9ce2d133d'}', status='Unknown'}.
```

The log is telling us that it moved to Unknown because to compensator kicked in because that command ended with failure. Because after the command completes the Storage Domain is no longer in Preparing For Maintenance status, it gets a different treatment by `IrsProxyImpl`.

While the command does "end with failure", we should not treat it as such because "Ignore OVF failure" was checked. So the easiest solution is to simply clear the compensation data created in `DeactivateStorageDomainWithOvfUpdateCommand#executeCommand`, by running: `getCompensationContext().cleanupCompensationDataAfterSuccessfulCommand()`in `DeactivateStorageDomainWithOvfUpdateCommand#endWithFailure`.

However, we can't simply run:
```java
    protected void endWithFailure() {
        if (commandCoordinatorUtil.getCommandExecutionStatus(getCommandId()) != CommandExecutionStatus.EXECUTED) {
            changeStorageDomainStatusInTransaction(loadStoragePoolIsoMap(), StorageDomainStatus.Unknown);
            auditLogDirector.log(this, AuditLogType.USER_DEACTIVATE_STORAGE_DOMAIN_OVF_UPDATE_INCOMPLETE);
        } else if (getParameters().isForceMaintenance()) {
            executeDeactivateCommand();
            getCompensationContext().cleanupCompensationDataAfterSuccessfulCommand();
        } else {
            auditLogDirector.log(this, AuditLogType.USER_DEACTIVATE_STORAGE_DOMAIN_FAILED);
        }

        setSucceeded(true);
    }
```
Because `endWithFailure` runs in a transaction, and the transaction includes the compensation so it will override the clearing code before it is persisted in the database. To make sure we reach the compensation code without anything to run compensation on, we have to wrap it in its own transaction:
```java
    protected void endWithFailure() {
        if (commandCoordinatorUtil.getCommandExecutionStatus(getCommandId()) != CommandExecutionStatus.EXECUTED) {
            changeStorageDomainStatusInTransaction(loadStoragePoolIsoMap(), StorageDomainStatus.Unknown);
            auditLogDirector.log(this, AuditLogType.USER_DEACTIVATE_STORAGE_DOMAIN_OVF_UPDATE_INCOMPLETE);
        } else if (getParameters().isForceMaintenance()) {
            executeDeactivateCommand();
            TransactionSupport.executeInNewTransaction(() -> {
                getCompensationContext().cleanupCompensationDataAfterSuccessfulCommand();
                return null;
            });
        } else {
            auditLogDirector.log(this, AuditLogType.USER_DEACTIVATE_STORAGE_DOMAIN_FAILED);
        }

        setSucceeded(true);
    }
```

Improvements:
Make sure `executeDeactivateCommand` was indeed successful, and only then clear the compensation data.

